# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [2]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [3]:
chipo_og = chipo.copy()

In [4]:
chipo["item_price"] = chipo["item_price"].str.replace("$", "")
chipo["item_price"] = chipo["item_price"].astype(float)
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [6]:
chipo["precio_unit"] = chipo["item_price"] / chipo["quantity"]

In [46]:
print(chipo.sort_values(by="item_price", ascending= False))

      order_id  quantity                     item_name  \
3598      1443        15  Chips and Fresh Tomato Salsa
3480      1398         3                 Carnitas Bowl
3602      1443         4               Chicken Burrito
1254       511         4               Chicken Burrito
3601      1443         3                Veggie Burrito
...        ...       ...                           ...
1057       435         1                   Canned Soda
117         51         1                   Canned Soda
2562      1014         1                   Canned Soda
2544      1009         1                   Canned Soda
2545      1009         1                 Bottled Water

                                     choice_description  item_price  \
3598                                                NaN       44.25
3480  [Roasted Chili Corn Salsa, [Fajita Vegetables,...       35.25
3602  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...       35.00
1254  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       35.00
3601  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       33.75
...                                                 ...         ...
1057                                     [Mountain Dew]        1.09
117                                   [Diet Dr. Pepper]        1.09
2562                                        [Coca Cola]        1.09
2544                                        [Diet Coke]        1.09
2545                                                NaN        1.09

      precio_unit
3598         2.95
3480        11.75
3602         8.75
1254         8.75
3601        11.25
...           ...
1057         1.09
117          1.09
2562         1.09
2544         1.09
2545         1.09

[4622 rows x 6 columns]

### Step 3. Name of the max valued product

In [ ]:
print(*chipo.loc[chipo["precio_unit"].idxmax(), ["item_name", "precio_unit"]])


prods_caros = chipo[chipo["precio_unit"] == chipo["precio_unit"].max()]

print(*prods_caros["item_name"].unique(), "- Precio:", prods_caros["precio_unit"].max())

Steak Salad Bowl 11.89
Steak Salad Bowl Carnitas Salad Bowl Barbacoa Salad Bowl - Precio: 11.89

### Step 4. How many products cost more than $10.00?

In [23]:
prods_diez = chipo[chipo["precio_unit"] > 10]

print(prods_diez["item_name"].count())

1034

In [24]:
print(chipo[chipo["precio_unit"] > 10].count())

order_id              1034
quantity              1034
item_name             1034
choice_description    1034
item_price            1034
precio_unit           1034
dtype: int64

In [25]:
print(chipo[chipo["precio_unit"] > 10].shape[0])

1034

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [31]:
print(prods_diez["order_id"].nunique())

787

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [32]:
total_pedido = chipo.groupby("order_id")["item_price"].sum()

cuenta = total_pedido[total_pedido > 10]
print(len(cuenta))

print()
print(total_pedido.sort_values())

1834

order_id
17       10.08
1379     10.08
388      10.08
889      10.08
393      10.08
         ...
1786    114.30
691     118.25
1483    139.00
1443    160.74
926     205.25
Name: item_price, Length: 1834, dtype: float64

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [33]:
mas_de_diez = chipo[chipo["item_price"] > 10]

print(mas_de_diez["order_id"].nunique())

863

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [34]:
chipo[["item_name", "precio_unit"]]

                                  item_name  precio_unit
0              Chips and Fresh Tomato Salsa         2.39
1                                      Izze         3.39
2                          Nantucket Nectar         3.39
3     Chips and Tomatillo-Green Chili Salsa         2.39
4                              Chicken Bowl         8.49
...                                     ...          ...
4617                          Steak Burrito        11.75
4618                          Steak Burrito        11.75
4619                     Chicken Salad Bowl        11.25
4620                     Chicken Salad Bowl         8.75
4621                     Chicken Salad Bowl         8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [36]:
chipo.sort_values(by="item_name")

,order_id,quantity,item_name,choice_description,item_price,precio_unit
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49
...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [41]:
lo_mas_pagado = chipo[chipo["item_price"] == chipo["item_price"].max()]

print(*lo_mas_pagado["quantity"])

15

In [42]:
chipo_ordenado = chipo.sort_values(by="item_price", ascending=False)

print(chipo_ordenado.iloc[0]["quantity"])

15

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [43]:
print(chipo[chipo["item_name"] == "Veggie Salad Bowl"]["quantity"].sum())

18

### Step 9. How many times did someone order more than one Canned Soda?

In [44]:
mas_de_una_lata = chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)]

print(len(mas_de_una_lata))

20